package cn.jbolt.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

import cn.jbolt.common.model.base.BaseCompanybusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Companybusiness extends BaseCompanybusiness<Companybusiness> {
	public static final Companybusiness dao = new Companybusiness().dao();
	
	public Page<Record> findByCompanyName(int page,String CompanyName){
		return Db.paginate(page,9, "select *","from companybusiness where CompanyName like '%"+CompanyName+"%'");
	}
	
	public Page<Record> findByShareholderName(int page,String ShareholderName){
		return Db.paginate(page,9, "select *","from companybusiness where shareholders like '%"+ShareholderName+"%'");
	}
}
